language: julia
os:
    - linux
    - osx
julia:
    - 0.7
    - 1.0
    - nightly
notifications:
    email: false
sudo: false
script:
    - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
    - julia -e 'import Pkg; Pkg.clone(pwd())'
    - julia -e 'import Pkg; Pkg.test("LibCURL", coverage=true)'
after_success:
    - julia -e 'import Pkg; cd(Pkg.dir("LibCURL")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'

