environment:
  matrix:
  - julia_version: 0.7
  - julia_version: 1.0
  - julia_version: latest

platform:
  - x86 # 32-bit
  - x64 # 64-bit

branches:
  only:
    - master
    - /release-.*/

notifications:
  - provider: Email
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: false

install:
  - ps: iex ((new-object net.webclient).DownloadString("https://raw.githubusercontent.com/JuliaCI/Appveyor.jl/version-1/bin/install.ps1"))

build_script:
# Need to convert from shallow to complete for Pkg.clone to work
  - IF EXIST .git\shallow (git fetch --unshallow)
  - C:\julia\bin\julia -e "versioninfo(); import Pkg;
      Pkg.clone(pwd(), \"LibCURL\"); Pkg.build(\"LibCURL\")"

test_script:
  - C:\julia\bin\julia -e "import Pkg; Pkg.test(\"LibCURL\")"
